repos:
  - repo: local
    hooks:
      - name: prettier-yaml
        id: prettier-yaml
        types: [yaml]
        language: system
        entry: prettier --write

      - name: shellcheck
        id: shellcheck
        files: '\.sh$'
        language: system
        entry: shellcheck

      - name: nixpkgs-fmt
        id: nixpkgs-fmt
        files: '\.nix$'
        language: system
        entry: nixpkgs-fmt